/**
 * 媒体：抖音登录 Cookie、应用内视频预览窗口。
 */

const { BrowserWindow, session } = require("electron");
const fs = require("fs");
const path = require("path");

const state = require("./state.cjs");
const { ytDlpCookiesPath } = require("./paths.cjs");

function mediaSession() {
  return session.fromPartition("persist:kongku-media");
}

function cookiesToNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Kongku Desktop. Do not share it.",
  ];
  for (const c of cookies) {
    let domain = String(c.domain || "").trim();
    if (!domain) continue;
    domain = domain.replace(/^\./, "");
    if (domain.startsWith("www.")) domain = domain.slice(4);
    domain = `.${domain}`;
    const includeSubdomains = "TRUE";
    const cookiePath = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry =
      typeof c.expirationDate === "number" && c.expirationDate > 0
        ? Math.floor(c.expirationDate)
        : 0;
    const name = c.name || "";
    const value = String(c.value ?? "").replace(/[\r\n\t]/g, "");
    if (!name) continue;
    lines.push(
      [domain, includeSubdomains, cookiePath, secure, String(expiry), name, value].join(
        "\t",
      ),
    );
  }
  return `${lines.join("\n")}\n`;
}

function isHttpUrl(url) {
  try {
    const u = new URL(url);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

async function douyinLoginCookieStats() {
  const ses = mediaSession();
  const all = await ses.cookies.get({});
  const related = all.filter((c) =>
    /douyin|iesdouyin|snssdk|byte(?:dance)?/i.test(String(c.domain || "")),
  );
  const names = new Set(related.map((c) => c.name));
  const loggedIn = [...names].some((n) =>
    /^(sessionid|sessionid_ss|sid_tt|sid_guard|uid_tt|uid_tt_ss|passport_csrf_token)$/i.test(
      n,
    ),
  );
  return { count: related.length, loggedIn, names: [...names] };
}

async function exportMediaCookiesFile() {
  const ses = mediaSession();
  const all = await ses.cookies.get({});
  const preferred = all.filter((c) =>
    /douyin|iesdouyin|tiktok|byte(?:dance)?|snssdk|capcut/i.test(
      String(c.domain || ""),
    ),
  );
  const use = preferred.length > 0 ? preferred : all;
  const out = ytDlpCookiesPath();
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, cookiesToNetscape(use), "utf8");
  const stats = await douyinLoginCookieStats();
  console.log(
    "[kongku] exported media cookies:",
    out,
    "count=",
    use.length,
    "loggedIn=",
    stats.loggedIn,
  );
  return {
    ok: true,
    path: out,
    count: use.length,
    loggedIn: stats.loggedIn,
    message: stats.loggedIn
      ? undefined
      : "未检测到登录 Cookie，请确认已在弹窗中登录抖音网页版后再关闭",
  };
}

function attachMediaLoginGuards(win) {
  const wc = win.webContents;
  wc.setUserAgent(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  );

  const blockDeepLink = (url, via) => {
    console.warn(`[kongku] blocked media deep link via ${via}:`, url);
  };

  // 禁止唤起抖音/头条 App（bytedance://、snssdk:// 等），否则系统弹「未设定用来打开 URL」
  wc.setWindowOpenHandler(({ url }) => {
    if (!isHttpUrl(url)) {
      blockDeepLink(url, "window.open");
      return { action: "deny" };
    }
    return {
      action: "allow",
      overrideBrowserWindowOptions: {
        autoHideMenuBar: true,
        webPreferences: {
          partition: "persist:kongku-media",
          contextIsolation: true,
          nodeIntegration: false,
          sandbox: true,
        },
      },
    };
  });

  const denyNonHttp = (event, url, via) => {
    if (url && !isHttpUrl(url)) {
      event.preventDefault();
      blockDeepLink(url, via);
    }
  };

  wc.on("will-navigate", (event, url) => denyNonHttp(event, url, "will-navigate"));
  wc.on("will-redirect", (event, url) => denyNonHttp(event, url, "will-redirect"));
  wc.on("will-frame-navigate", (event) => {
    denyNonHttp(event, event.url, "will-frame-navigate");
  });

  wc.on("did-create-window", (child) => {
    attachMediaLoginGuards(child);
  });
}

function openMediaLoginWindow(site = "douyin") {
  const startUrl =
    site === "tiktok"
      ? "https://www.tiktok.com/login"
      : "https://www.douyin.com/?recommend=1";

  if (state.mediaLoginWindow && !state.mediaLoginWindow.isDestroyed()) {
    state.mediaLoginWindow.focus();
    void state.mediaLoginWindow.loadURL(startUrl);
    return { ok: true, reused: true };
  }

  state.mediaLoginWindow = new BrowserWindow({
    width: 1080,
    height: 780,
    parent:
      state.mainWindow && !state.mainWindow.isDestroyed()
        ? state.mainWindow
        : undefined,
    modal: false,
    autoHideMenuBar: true,
    title: "空库 · 请在网页登录抖音，完成后关闭本窗口",
    webPreferences: {
      partition: "persist:kongku-media",
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  state.mediaLoginWindow.setMenuBarVisibility(false);
  attachMediaLoginGuards(state.mediaLoginWindow);
  void state.mediaLoginWindow.loadURL(startUrl);

  let loginPoll = null;
  const stopPoll = () => {
    if (loginPoll) {
      clearInterval(loginPoll);
      loginPoll = null;
    }
  };
  loginPoll = setInterval(() => {
    void (async () => {
      try {
        const stats = await douyinLoginCookieStats();
        if (!stats.loggedIn) return;
        stopPoll();
        const info = await exportMediaCookiesFile();
        state.mainWindow?.webContents.send("media:cookies-exported", {
          ...info,
          message:
            "已检测到抖音登录，Cookie 已保存。可关闭登录窗口并对失败项点「重试」。",
        });
      } catch (err) {
        console.warn("[kongku] login poll:", err);
      }
    })();
  }, 2000);

  state.mediaLoginWindow.on("closed", () => {
    stopPoll();
    state.mediaLoginWindow = null;
    void exportMediaCookiesFile()
      .then((info) => {
        state.mainWindow?.webContents.send("media:cookies-exported", info);
      })
      .catch((err) => {
        state.mainWindow?.webContents.send("media:cookies-exported", {
          ok: false,
          message: String(err?.message || err),
        });
      });
  });

  return { ok: true, reused: false };
}

function openVideoPreviewWindow(rawUrl, title = "") {
  const url = String(rawUrl || "").trim();
  if (!isHttpUrl(url)) {
    return { ok: false, message: "无效的视频链接" };
  }

  const winTitle = title
    ? `空库 · ${String(title).slice(0, 60)}`
    : "空库 · 视频预览";

  if (state.mediaPreviewWindow && !state.mediaPreviewWindow.isDestroyed()) {
    state.mediaPreviewWindow.setTitle(winTitle);
    state.mediaPreviewWindow.focus();
    void state.mediaPreviewWindow.loadURL(url);
    return { ok: true, reused: true };
  }

  state.mediaPreviewWindow = new BrowserWindow({
    width: 960,
    height: 680,
    minWidth: 720,
    minHeight: 480,
    parent:
      state.mainWindow && !state.mainWindow.isDestroyed()
        ? state.mainWindow
        : undefined,
    modal: false,
    autoHideMenuBar: true,
    title: winTitle,
    webPreferences: {
      partition: "persist:kongku-media",
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  state.mediaPreviewWindow.setMenuBarVisibility(false);
  attachMediaLoginGuards(state.mediaPreviewWindow);
  void state.mediaPreviewWindow.loadURL(url);
  state.mediaPreviewWindow.on("closed", () => {
    state.mediaPreviewWindow = null;
  });

  return { ok: true, reused: false };
}

module.exports = {
  mediaSession,
  isHttpUrl,
  attachMediaLoginGuards,
  exportMediaCookiesFile,
  openMediaLoginWindow,
  openVideoPreviewWindow,
};
