/**
 * 媒体：抖音 / B站登录 Cookie、应用内视频预览窗口。
 */

const { BrowserWindow, session } = require("electron");
const fs = require("fs");
const path = require("path");

const state = require("./state.cjs");
const { ytDlpCookiesPath } = require("./paths.cjs");

const SITE_PRESETS = {
  douyin: {
    startUrl: "https://www.douyin.com/?recommend=1",
    title: "空库 · 请在网页登录抖音，完成后关闭本窗口",
    label: "抖音",
  },
  bilibili: {
    startUrl: "https://www.bilibili.com/",
    title: "空库 · 请在网页登录B站，完成后关闭本窗口",
    label: "B站",
  },
  tiktok: {
    startUrl: "https://www.tiktok.com/login",
    title: "空库 · 请在网页登录 TikTok，完成后关闭本窗口",
    label: "TikTok",
  },
};

function mediaSession() {
  return session.fromPartition("persist:kongku-media");
}

function cookiesToNetscape(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# This file was generated by Kongku Desktop. Do not share it.",
  ];
  for (const c of cookies) {
    let domain = String(c.domain || "").trim();
    if (!domain) continue;
    domain = domain.replace(/^\./, "");
    if (domain.startsWith("www.")) domain = domain.slice(4);
    domain = `.${domain}`;
    const includeSubdomains = "TRUE";
    const cookiePath = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry =
      typeof c.expirationDate === "number" && c.expirationDate > 0
        ? Math.floor(c.expirationDate)
        : 0;
    const name = c.name || "";
    const value = String(c.value ?? "").replace(/[\r\n\t]/g, "");
    if (!name) continue;
    lines.push(
      [domain, includeSubdomains, cookiePath, secure, String(expiry), name, value].join(
        "\t",
      ),
    );
  }
  return `${lines.join("\n")}\n`;
}

function isHttpUrl(url) {
  try {
    const u = new URL(url);
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

function isDouyinCookie(c) {
  return /douyin|iesdouyin|snssdk|byte(?:dance)?|tiktok|capcut/i.test(
    String(c.domain || ""),
  );
}

function isBilibiliCookie(c) {
  return /bilibili|bilivideo|b23\.tv/i.test(String(c.domain || ""));
}

function isMediaCookie(c) {
  return isDouyinCookie(c) || isBilibiliCookie(c);
}

async function douyinLoginCookieStats() {
  const ses = mediaSession();
  const all = await ses.cookies.get({});
  const related = all.filter(isDouyinCookie);
  const names = new Set(related.map((c) => c.name));
  const loggedIn = [...names].some((n) =>
    /^(sessionid|sessionid_ss|sid_tt|sid_guard|uid_tt|uid_tt_ss|passport_csrf_token)$/i.test(
      n,
    ),
  );
  return { count: related.length, loggedIn, names: [...names] };
}

async function bilibiliLoginCookieStats() {
  const ses = mediaSession();
  const all = await ses.cookies.get({});
  const related = all.filter(isBilibiliCookie);
  const names = new Set(related.map((c) => c.name));
  const loggedIn = [...names].some((n) =>
    /^(SESSDATA|bili_jct|DedeUserID|DedeUserID__ckMd5)$/i.test(n),
  );
  return { count: related.length, loggedIn, names: [...names] };
}

async function mediaLoginCookieStats(site = "douyin") {
  if (site === "bilibili") return bilibiliLoginCookieStats();
  return douyinLoginCookieStats();
}

async function exportMediaCookiesFile(siteHint = "") {
  const ses = mediaSession();
  const all = await ses.cookies.get({});
  // 同时保留抖音 + B站域，避免登录一侧时冲掉另一侧
  const preferred = all.filter(isMediaCookie);
  const use = preferred.length > 0 ? preferred : all;
  const out = ytDlpCookiesPath();
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, cookiesToNetscape(use), "utf8");
  const douyin = await douyinLoginCookieStats();
  const bilibili = await bilibiliLoginCookieStats();
  const hint = String(siteHint || "").toLowerCase();
  const focus =
    hint === "bilibili"
      ? bilibili
      : hint === "douyin" || hint === "tiktok"
        ? douyin
        : { loggedIn: douyin.loggedIn || bilibili.loggedIn, count: use.length };
  console.log(
    "[kongku] exported media cookies:",
    out,
    "count=",
    use.length,
    "douyinLoggedIn=",
    douyin.loggedIn,
    "bilibiliLoggedIn=",
    bilibili.loggedIn,
  );
  let message;
  if (hint === "bilibili" && !bilibili.loggedIn) {
    message = "未检测到 B站登录 Cookie，请确认已在弹窗中登录 B站网页版后再关闭";
  } else if ((hint === "douyin" || hint === "tiktok") && !douyin.loggedIn) {
    message = "未检测到登录 Cookie，请确认已在弹窗中登录抖音网页版后再关闭";
  }
  return {
    ok: true,
    path: out,
    count: use.length,
    loggedIn: Boolean(focus.loggedIn),
    site: hint || undefined,
    douyinLoggedIn: douyin.loggedIn,
    bilibiliLoggedIn: bilibili.loggedIn,
    douyinCount: douyin.count,
    bilibiliCount: bilibili.count,
    message,
  };
}

function attachMediaLoginGuards(win) {
  const wc = win.webContents;
  wc.setUserAgent(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
  );

  const blockDeepLink = (url, via) => {
    console.warn(`[kongku] blocked media deep link via ${via}:`, url);
  };

  // 禁止唤起抖音/头条 App（bytedance://、snssdk:// 等），否则系统弹「未设定用来打开 URL」
  wc.setWindowOpenHandler(({ url }) => {
    if (!isHttpUrl(url)) {
      blockDeepLink(url, "window.open");
      return { action: "deny" };
    }
    return {
      action: "allow",
      overrideBrowserWindowOptions: {
        autoHideMenuBar: true,
        webPreferences: {
          partition: "persist:kongku-media",
          contextIsolation: true,
          nodeIntegration: false,
          sandbox: true,
        },
      },
    };
  });

  const denyNonHttp = (event, url, via) => {
    if (url && !isHttpUrl(url)) {
      event.preventDefault();
      blockDeepLink(url, via);
    }
  };

  wc.on("will-navigate", (event, url) => denyNonHttp(event, url, "will-navigate"));
  wc.on("will-redirect", (event, url) => denyNonHttp(event, url, "will-redirect"));
  wc.on("will-frame-navigate", (event) => {
    denyNonHttp(event, event.url, "will-frame-navigate");
  });

  wc.on("did-create-window", (child) => {
    attachMediaLoginGuards(child);
  });
}

function openMediaLoginWindow(site = "douyin") {
  const key = SITE_PRESETS[site] ? site : "douyin";
  const preset = SITE_PRESETS[key];
  const startUrl = preset.startUrl;

  if (state.mediaLoginWindow && !state.mediaLoginWindow.isDestroyed()) {
    state.mediaLoginWindow.setTitle(preset.title);
    state.mediaLoginWindow.focus();
    void state.mediaLoginWindow.loadURL(startUrl);
    state.mediaLoginSite = key;
    return { ok: true, reused: true, site: key };
  }

  state.mediaLoginSite = key;
  state.mediaLoginWindow = new BrowserWindow({
    width: 1080,
    height: 780,
    parent:
      state.mainWindow && !state.mainWindow.isDestroyed()
        ? state.mainWindow
        : undefined,
    modal: false,
    autoHideMenuBar: true,
    title: preset.title,
    webPreferences: {
      partition: "persist:kongku-media",
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  state.mediaLoginWindow.setMenuBarVisibility(false);
  attachMediaLoginGuards(state.mediaLoginWindow);
  void state.mediaLoginWindow.loadURL(startUrl);

  let loginPoll = null;
  const stopPoll = () => {
    if (loginPoll) {
      clearInterval(loginPoll);
      loginPoll = null;
    }
  };
  loginPoll = setInterval(() => {
    void (async () => {
      try {
        const currentSite = state.mediaLoginSite || key;
        const stats = await mediaLoginCookieStats(currentSite);
        if (!stats.loggedIn) return;
        stopPoll();
        const info = await exportMediaCookiesFile(currentSite);
        const label = SITE_PRESETS[currentSite]?.label || currentSite;
        state.mainWindow?.webContents.send("media:cookies-exported", {
          ...info,
          site: currentSite,
          message:
            info.message ||
            `已检测到${label}登录，Cookie 已保存。可关闭登录窗口并对失败项点「重试」。`,
        });
      } catch (err) {
        console.warn("[kongku] login poll:", err);
      }
    })();
  }, 2000);

  state.mediaLoginWindow.on("closed", () => {
    const closedSite = state.mediaLoginSite || key;
    stopPoll();
    state.mediaLoginWindow = null;
    state.mediaLoginSite = null;
    void exportMediaCookiesFile(closedSite)
      .then((info) => {
        state.mainWindow?.webContents.send("media:cookies-exported", {
          ...info,
          site: closedSite,
        });
      })
      .catch((err) => {
        state.mainWindow?.webContents.send("media:cookies-exported", {
          ok: false,
          site: closedSite,
          message: String(err?.message || err),
        });
      });
  });

  return { ok: true, reused: false, site: key };
}

function openVideoPreviewWindow(rawUrl, title = "") {
  const url = String(rawUrl || "").trim();
  if (!isHttpUrl(url)) {
    return { ok: false, message: "无效的视频链接" };
  }

  const winTitle = title
    ? `空库 · ${String(title).slice(0, 60)}`
    : "空库 · 视频预览";

  if (state.mediaPreviewWindow && !state.mediaPreviewWindow.isDestroyed()) {
    state.mediaPreviewWindow.setTitle(winTitle);
    state.mediaPreviewWindow.focus();
    void state.mediaPreviewWindow.loadURL(url);
    return { ok: true, reused: true };
  }

  state.mediaPreviewWindow = new BrowserWindow({
    width: 960,
    height: 680,
    minWidth: 720,
    minHeight: 480,
    parent:
      state.mainWindow && !state.mainWindow.isDestroyed()
        ? state.mainWindow
        : undefined,
    modal: false,
    autoHideMenuBar: true,
    title: winTitle,
    webPreferences: {
      partition: "persist:kongku-media",
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });

  state.mediaPreviewWindow.setMenuBarVisibility(false);
  attachMediaLoginGuards(state.mediaPreviewWindow);
  void state.mediaPreviewWindow.loadURL(url);
  state.mediaPreviewWindow.on("closed", () => {
    state.mediaPreviewWindow = null;
  });

  return { ok: true, reused: false };
}

module.exports = {
  mediaSession,
  isHttpUrl,
  attachMediaLoginGuards,
  exportMediaCookiesFile,
  openMediaLoginWindow,
  openVideoPreviewWindow,
  douyinLoginCookieStats,
  bilibiliLoginCookieStats,
};
